//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityOrganisation.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int idDonation { get; set; }
        public int idUser { get; set; }
        public decimal amount { get; set; }
        public System.DateTime timeDonated { get; set; }
        public int charitableCauseId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int anonymous { get; set; }
        public int creditCard { get; set; }
        public int csc { get; set; }
    }
}
