//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityOrganisation.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int idEvent { get; set; }
        public string event1 { get; set; }
        public int idUser { get; set; }
        public System.DateTime eventTime { get; set; }
    }
}
