//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityOrganisation.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int idImage { get; set; }
        public string imageName { get; set; }
        public string path { get; set; }
        public string thumbPath { get; set; }
    }
}
