//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityOrganisation.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollAnswer
    {
        public int idPollAnswer { get; set; }
        public string pollAnswer1 { get; set; }
        public int answerScore { get; set; }
        public int idPollQuestion { get; set; }
    }
}
